repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-all]

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.270
    hooks:
    -   id: ruff

-   repo: https://github.com/MrPowers/chispa
    rev: v0.10.1
    hooks:
    -   id: pytest
