name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
#
#    - name: Create and activate virtual environment
#      run: |
#        python -m venv venv
#        echo "VIRTUAL_ENV=${{ github.workspace }}/venv" >> $GITHUB_ENV
#        echo "${{ github.workspace }}/venv/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pre-commit hooks
      uses: pre-commit/action@v3.0.0
      with:
          extra_args: --files src/**/*

    - name: Lint and format code (with fixes)
      run: |
        ruff check src --fix
        ruff format src

    - name: Run type checks
      run: |
        mypy src

    - name: Run tests
      run: |
        pytest

    - name: Build distribution
      run: |
        python -m build

    - name: Upload distribution
      uses: actions/upload-artifact@v3
      with:
        name: distribution
        path: |
          dist/*.tar.gz
          dist/*.whl

    - name: Install the package in editable mode
      run: |
          pip install -e .

#    - name: Run sales-data
#      run: |
#          python -c "import sys; print(sys.path)"
#          python -c "import src; print(src.__file__)"
#          sales-data
#          working-directory: ${{ github.workspace }}
#    - name: Run sales-data
#      run: |
#        python -c "import sys; print(sys.path)"
#        python -c "import src; print(src.__file__)"
#        python -c "from src.main import main; main()"
#      working-directory: ${{ github.workspace }}

#    - name: Run sales-data
#      run: |
#        python -m src.main
#      env:
#        PYTHONPATH: ${{ github.workspace }}
    - name: Run script
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        python -m src.main